language: node_js
node_js:
  - "stable"
  - "6"
notifications:
  email:
  - xdenser@gmail.com  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq firebird2.5-superclassic firebird2.5-dev
  - sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
  - cat /etc/default/firebird2.5 | grep ENABLE_FIREBIRD_SERVER
  - sudo service firebird2.5-superclassic start

